### ISSUE TITLE
E2E PageObject pattern

### ISSUE THREAD

**Issue by ok2ju** [menkuichan/super-enigma-fe#29]
Refactor e2e tests using PageObject pattern.
Sources (explanations):
1. https://stackoverflow.com/questions/48216151/page-object-mode-with-node-es7-puppeteer (see answer);
2. https://github.com/just-boris/page-object (functional approach);
3. https://github.com/puppeteer/puppeteer/issues/1782#issuecomment-357089464

**Comment by menkuichan** [comment]
Closed at #35 #34 #33 #32
